[build-system]
requires = ["setuptools", "pip", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sd_webui_all_in_one"
description = "支持部署多个 WebUI 的部署工具"
requires-python = ">=3.10"
readme = { content-type = "text/markdown", file = "README.md" }
license = { file = "LICENSE" }
dynamic = ["version"]
version = "1.1.18"
authors = [{name = "licyk"}]

[tool.setuptools]
py_modules = ["sd_webui_all_in_one"]

[tool.pylint]
disable = [
    "missing-timeout",
    "too-many-lines",
    "import-outside-toplevel",
    "broad-exception-caught",
    "broad-exception-raised",
    "subprocess-run-check",
    "keyword-arg-before-vararg",
    "fixme"
]

[tool.pylint.format]
max-line-length = 180
ignore-long-lines = "^\\s*(# )?<?https?://\\S+>?$"