name: Ruff Lint

on:
  push:
    paths:
      - sd_webui_all_in_one
  workflow_dispatch:

jobs:
  Ruff-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3
        with:
          src: >-
            sd_webui_all_in_one
